export const MY_LOCATION_PLACE_NAME = 'myLocationPlaceName';
export const MY_LOCATION = 'myLocation';
export const DISPENSARY_VIEW = 'dispensaryview'
export const ARTICLE_VIEW = 'articleview'
export const ACCEPT_TERMS = 'acceptedTerms'
export const ENABLE_GEOLOCATION = 'enableGeolocation'
export const ACCEPT_COOKIES = 'acceptCookies'
export const MY_LOCATION_PLACE= 'myLocationPlace'
export const LOCAL_CART = 'localCart'
export const ENTITY_CART = 'entityCart'
export const BACKGROUND_STATE = 'backgroundState'
export const DISABLE_GEOLOCATION = 'disableGeolocation'
export const MY_LOCATION_PLACE_FULLNAME = 'MY_LOCATION_PLACE_FULLNAME'