export const effectsIcons = {
    aroused: `/assets/emojis/effects/aroused.svg`,
    creative: `/assets/emojis/effects/creative.svg`,
    energetic: `/assets/emojis/effects/energetic.svg`,
    euphoric: `/assets/emojis/effects/euphoric.svg`,
    focused: `/assets/emojis/effects/focused.svg`,
    giggly: `/assets/emojis/effects/giggly.svg`,
    happy: `/assets/emojis/effects/happy.svg`,
    hungry: `/assets/emojis/effects/hungry.svg`,
    relaxed: `/assets/emojis/effects/relaxed.svg`,
    sleepy: `/assets/emojis/effects/relaxed.svg`,
    talkative: `/assets/emojis/effects/talkative.svg`,
    tingly: `/assets/emojis/effects/tingly.svg`,
    uplifted: `/assets/emojis/effects/uplifted.svg` 
}

export const flavorsIcons = {
    'ammonia': `/assets/emojis/flavors/ammonia.svg`,
    'apple': `/assets/emojis/flavors/apple.svg`,
    'apricot': `/assets/emojis/flavors/apricot.svg`,
    'berry': `/assets/emojis/flavors/berry.svg`,
    'blue cheese': `/assets/emojis/flavors/bluecheese.svg`,
    'blueberry': `/assets/emojis/flavors/blueberry.svg`,
    'cheese': `/assets/emojis/flavors/cheese.svg`,
    'chemical': `/assets/emojis/flavors/chemical.svg`,
    'chestnut': `/assets/emojis/flavors/chestnut.svg`,
    'citrus': `/assets/emojis/flavors/citrus.svg`,
    'coffee': `/assets/emojis/flavors/coffee.svg`,
    'diesel': `/assets/emojis/flavors/diesel.svg`,
    'earthy': `/assets/emojis/flavors/earthy.svg`,
    'flowery': `/assets/emojis/flavors/flowery.svg`,
    'grape': `/assets/emojis/flavors/grape.svg`,
    'grapefruit': `/assets/emojis/flavors/grapefruit.svg`,
    'honey': `/assets/emojis/flavors/honey.svg`,
    'lavender': `/assets/emojis/flavors/lavender.svg`,
    'lemon': `/assets/emojis/flavors/lemon.svg`,
    'lime': `/assets/emojis/flavors/lime.svg`,
    'mango': `/assets/emojis/flavors/mango.svg`,
    'mint': `/assets/emojis/flavors/mint.svg`,
    'nutty': `/assets/emojis/flavors/nutty.svg`,
    'orange': `/assets/emojis/flavors/orange.svg`,
    'peach': `/assets/emojis/flavors/peach.svg`,
    'pear': `/assets/emojis/flavors/pear.svg`,
    'pepper': `/assets/emojis/flavors/pepper.svg`,
    'pine': `/assets/emojis/flavors/pine.svg`,
    'pineapple': `/assets/emojis/flavors/pineapple.svg`,
    'plum': `/assets/emojis/flavors/plum.svg`,
    'pungent': `/assets/emojis/flavors/pungent.svg`,
    'rose': `/assets/emojis/flavors/rose.svg`,
    'sage': `/assets/emojis/flavors/sage.svg`,
    'skunk': `/assets/emojis/flavors/skunk.svg`,
    'herbal': `/assets/emojis/flavors/herbal.svg`,
    'strawberry': `/assets/emojis/flavors/strawberry.svg`,
    'sweet': `/assets/emojis/flavors/sweet.svg`,
    'tar': `/assets/emojis/flavors/tar.svg`,
    'tea': `/assets/emojis/flavors/tea.svg`,
    'tobacco': `/assets/emojis/flavors/tobacco.svg`,
    'tree fruit': `/assets/emojis/flavors/treefruit.svg`,
    'tropical': `/assets/emojis/flavors/tropical.svg`,
    'vanilla': `/assets/emojis/flavors/vanilla.svg`,
    'woody': `/assets/emojis/flavors/woody.svg`,
}
